<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>

<div class="mid_colum">
      <div class="colum_content first_colum">
        <div class="colum_head">Cheap <br />
          <span>Delivery</span> </div>
        <div class="colum_midpart"> <img src="<?php echo $this->getSkinUrl('images/laptops.jpg') ; ?>" alt="" />
          <div class="colum_bottombar"><a href="#">Laptops > </a></div>
        </div>
      </div>
      <div class="colum_content  second_colum">
        <div class="colum_head">Lowest<br />
          <span>Market Prices</span> </div>
        <div class="colum_midpart"> <img src="<?php echo $this->getSkinUrl('images/img_2.jpg') ; ?>" alt="" />
          <div class="colum_bottombar"><a href="#">Desktops > </a></div>
        </div>
      </div>
      <div class="colum_content second_colum">
        <div class="colum_head">Massive<br />
          <span>Product Range</span> </div>
        <div class="colum_midpart"> <img src="<?php echo $this->getSkinUrl('images/img_3.jpg') ; ?>" alt="" />
          <div class="colum_bottombar"><a href="#">Servers > </a></div>
        </div>
      </div>
      <div class="colum_content second_colum">
        <div class="colum_headlast"><img src="<?php echo $this->getSkinUrl('images/perferred_partner.jpg') ; ?>" alt=""  /></div>
        <div class="colum_midpart"> <img src="<?php echo $this->getSkinUrl('images/img_4.jpg') ; ?>" alt="" />
          <div class="colum_bottombar"><a href="#">Printers > </a></div>
        </div>
      </div>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>